name: crypto_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  intl: ^0.17.0
  lottie: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_charts: ^19.1.54
  url_launcher: ^6.1.7
  simple_gradient_text: ^1.2.4
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/logo/

  fonts:
    - family: "MontserratAlternates"
      fonts:
        - asset: "assets/fonts/MontserratAlternates-Regular.ttf"
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
